name: Docker publish images

on:
  # schedule:
    # - cron: '15 0 * * 1' # Weekly on Monday at 00:15
  
  workflow_dispatch:
  
env:
  IMAGE_NAME: "elasticsearch"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elastictag: ['7.9.3', '7.12.0']
    name: Publish Elasticsearch v${{ matrix.elastictag }} images to GitHub and DockerHub Container Registries
    if: (github.ref == 'refs/heads/main')
        || (github.event_name == 'schedule')

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: refs/heads/main

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file Dockerfile --build-arg ELASTICTAG=${{ matrix.elastictag }}
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub Container Registry
        uses: docker/login-action@v1.9.0 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.9.0 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Get version information
        id: image_information
        run: |
          IMAGE_ID=${{ github.repository_owner }}/${{ env.IMAGE_NAME }}

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Get version from ELASTICTAG
          VERSION=${{ matrix.elastictag }}

          echo ::set-output name=IMAGE_ID::${IMAGE_ID}
          echo ::set-output name=IMAGE_REF::${VERSION}

      - name: Build and push Docker images
        if: ${{ steps.image_information.outputs.IMAGE_REF }} != 'latest'
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            ELASTICTAG=${{ matrix.elastictag }}
          tags: |
            ${{ steps.image_information.outputs.IMAGE_ID }}:${{ steps.image_information.outputs.IMAGE_REF }}
            ghcr.io/${{ steps.image_information.outputs.IMAGE_ID }}:${{ steps.image_information.outputs.IMAGE_REF }}
